// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCaipKmqOI0ltLgIOS7V8-fiofluL4rqQ',
    appId: '1:241076890596:web:7d40d67bd2c0de7d1f75f1',
    messagingSenderId: '241076890596',
    projectId: 'csen-f24-g6',
    authDomain: 'csen-f24-g6.firebaseapp.com',
    storageBucket: 'csen-f24-g6.firebasestorage.app',
    measurementId: 'G-QKQC628WGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF68Q-K4D1dwtVuRhguNoos9LwLfHkI4w',
    appId: '1:241076890596:android:ace289f1acc107ac1f75f1',
    messagingSenderId: '241076890596',
    projectId: 'csen-f24-g6',
    storageBucket: 'csen-f24-g6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6wR8r0bBJ5oMl_CKugtLc-pFcc-VePk',
    appId: '1:241076890596:ios:eb2acf6898d5fa881f75f1',
    messagingSenderId: '241076890596',
    projectId: 'csen-f24-g6',
    storageBucket: 'csen-f24-g6.firebasestorage.app',
    iosBundleId: 'com.example.csen268F24G6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6wR8r0bBJ5oMl_CKugtLc-pFcc-VePk',
    appId: '1:241076890596:ios:eb2acf6898d5fa881f75f1',
    messagingSenderId: '241076890596',
    projectId: 'csen-f24-g6',
    storageBucket: 'csen-f24-g6.firebasestorage.app',
    iosBundleId: 'com.example.csen268F24G6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCaipKmqOI0ltLgIOS7V8-fiofluL4rqQ',
    appId: '1:241076890596:web:932a0ca94c94c96d1f75f1',
    messagingSenderId: '241076890596',
    projectId: 'csen-f24-g6',
    authDomain: 'csen-f24-g6.firebaseapp.com',
    storageBucket: 'csen-f24-g6.firebasestorage.app',
    measurementId: 'G-HR39K3WMRH',
  );
}
